In [40]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import tree
from sklearn.metrics import confusion_matrix
import pickle

In [5]:
df = pd.read_csv("./uci_malware_detection.csv")

In [6]:
df

,Label,F_1,F_2,F_3,F_4,F_5,F_6,F_7,F_8,F_9,...,F_522,F_523,F_524,F_525,F_526,F_527,F_528,F_529,F_530,F_531
0,non-malicious,1,0,1,0,1,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
1,non-malicious,1,0,1,0,1,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
2,non-malicious,1,0,1,0,1,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
3,non-malicious,1,0,1,0,1,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
4,non-malicious,1,0,1,0,1,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
368,malicious,1,0,1,0,1,0,1,0,1,...,0,0,0,0,0,0,0,1,0,1
369,malicious,1,0,1,0,1,0,1,0,1,...,0,0,0,1,0,0,0,0,1,0
370,malicious,1,0,1,0,1,0,1,0,1,...,1,0,0,0,1,0,0,0,1,0
371,malicious,1,0,1,0,1,0,1,0,1,...,0,0,0,0,1,0,0,0,1,0
372,malicious,1,0,1,0,1,0,1,0,1,...,0,0,0,1,0,0,0,0,0,1

In [8]:
df.head()

,Label,F_1,F_2,F_3,F_4,F_5,F_6,F_7,F_8,F_9,...,F_522,F_523,F_524,F_525,F_526,F_527,F_528,F_529,F_530,F_531
0,non-malicious,1,0,1,0,1,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
1,non-malicious,1,0,1,0,1,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
2,non-malicious,1,0,1,0,1,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
3,non-malicious,1,0,1,0,1,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
4,non-malicious,1,0,1,0,1,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0

In [9]:
df.tail()

,Label,F_1,F_2,F_3,F_4,F_5,F_6,F_7,F_8,F_9,...,F_522,F_523,F_524,F_525,F_526,F_527,F_528,F_529,F_530,F_531
368,malicious,1,0,1,0,1,0,1,0,1,...,0,0,0,0,0,0,0,1,0,1
369,malicious,1,0,1,0,1,0,1,0,1,...,0,0,0,1,0,0,0,0,1,0
370,malicious,1,0,1,0,1,0,1,0,1,...,1,0,0,0,1,0,0,0,1,0
371,malicious,1,0,1,0,1,0,1,0,1,...,0,0,0,0,1,0,0,0,1,0
372,malicious,1,0,1,0,1,0,1,0,1,...,0,0,0,1,0,0,0,0,0,1

In [10]:
df.describe()

,F_1,F_2,F_3,F_4,F_5,F_6,F_7,F_8,F_9,F_10,...,F_522,F_523,F_524,F_525,F_526,F_527,F_528,F_529,F_530,F_531
count,373.000000,373.0,373.000000,373.000000,373.000000,373.0,373.000000,373.0,373.000000,373.0,...,373.00000,373.000000,373.000000,373.000000,373.000000,373.000000,373.000000,373.000000,373.000000,373.000000
mean,0.997319,0.0,0.994638,0.002681,0.994638,0.0,0.994638,0.0,0.994638,0.0,...,0.10992,0.107239,0.088472,0.099196,0.522788,0.040214,0.091153,0.080429,0.530831,0.144772
std,0.051778,0.0,0.073127,0.051778,0.073127,0.0,0.073127,0.0,0.073127,0.0,...,0.31321,0.309832,0.284361,0.299326,0.500151,0.196726,0.288213,0.272321,0.499719,0.352344
min,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.0,...,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.000000,0.0,1.000000,0.000000,1.000000,0.0,1.000000,0.0,1.000000,0.0,...,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,1.000000,0.0,1.000000,0.000000,1.000000,0.0,1.000000,0.0,1.000000,0.0,...,0.00000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000
75%,1.000000,0.0,1.000000,0.000000,1.000000,0.0,1.000000,0.0,1.000000,0.0,...,0.00000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000
max,1.000000,0.0,1.000000,1.000000,1.000000,0.0,1.000000,0.0,1.000000,0.0,...,1.00000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [11]:
def is_malware(X):
    return True

    return False

In [12]:
y= df["Label"]
y

0      non-malicious
1      non-malicious
2      non-malicious
3      non-malicious
4      non-malicious
           ...
368        malicious
369        malicious
370        malicious
371        malicious
372        malicious
Name: Label, Length: 373, dtype: object

In [13]:
X=df.drop("Label",axis=1)
X

,F_1,F_2,F_3,F_4,F_5,F_6,F_7,F_8,F_9,F_10,...,F_522,F_523,F_524,F_525,F_526,F_527,F_528,F_529,F_530,F_531
0,1,0,1,0,1,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
1,1,0,1,0,1,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,1,0,1,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
3,1,0,1,0,1,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
4,1,0,1,0,1,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
368,1,0,1,0,1,0,1,0,1,0,...,0,0,0,0,0,0,0,1,0,1
369,1,0,1,0,1,0,1,0,1,0,...,0,0,0,1,0,0,0,0,1,0
370,1,0,1,0,1,0,1,0,1,0,...,1,0,0,0,1,0,0,0,1,0
371,1,0,1,0,1,0,1,0,1,0,...,0,0,0,0,1,0,0,0,1,0
372,1,0,1,0,1,0,1,0,1,0,...,0,0,0,1,0,0,0,0,0,1

In [14]:
X.loc[1]

F_1      1
F_2      0
F_3      1
F_4      0
F_5      1
        ..
F_527    0
F_528    0
F_529    0
F_530    0
F_531    0
Name: 1, Length: 531, dtype: int64

In [16]:
is_malware(X.loc[0])

True

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [21]:
X_train

,F_1,F_2,F_3,F_4,F_5,F_6,F_7,F_8,F_9,F_10,...,F_522,F_523,F_524,F_525,F_526,F_527,F_528,F_529,F_530,F_531
36,1,0,1,0,1,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
158,1,0,1,0,1,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,1
183,1,0,1,0,1,0,1,0,1,0,...,0,0,0,0,1,0,0,0,1,0
168,1,0,1,0,1,0,1,0,1,0,...,0,1,0,0,1,0,0,1,0,0
302,1,0,1,0,1,0,1,0,1,0,...,0,1,0,0,1,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71,1,0,1,0,1,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
106,1,0,1,0,1,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
270,1,0,1,0,1,0,1,0,1,0,...,0,0,0,0,1,0,0,0,1,0
348,1,0,1,0,1,0,1,0,1,0,...,0,0,0,0,1,0,0,0,1,0
102,1,0,1,0,1,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,1

In [22]:
y_train

36     non-malicious
158        malicious
183        malicious
168        malicious
302        malicious
           ...
71     non-malicious
106        malicious
270        malicious
348        malicious
102        malicious
Name: Label, Length: 249, dtype: object

In [23]:
X_test

,F_1,F_2,F_3,F_4,F_5,F_6,F_7,F_8,F_9,F_10,...,F_522,F_523,F_524,F_525,F_526,F_527,F_528,F_529,F_530,F_531
327,1,0,1,0,1,0,1,0,1,0,...,0,0,0,0,1,0,0,0,1,0
33,1,0,1,0,1,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
15,1,0,1,0,1,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
314,1,0,1,0,1,0,1,0,1,0,...,0,0,0,0,1,0,0,0,1,0
57,1,0,1,0,1,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104,1,0,1,0,1,0,1,0,1,0,...,0,0,0,0,1,0,0,0,1,0
285,1,0,1,0,1,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,1
118,1,0,1,0,1,0,1,0,1,0,...,0,0,1,0,1,0,0,0,1,0
352,1,0,1,0,1,0,1,0,1,0,...,0,0,0,0,1,0,0,0,1,0
31,1,0,1,0,1,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0

In [24]:
y_test

327        malicious
33     non-malicious
15     non-malicious
314        malicious
57     non-malicious
           ...
104        malicious
285        malicious
118        malicious
352        malicious
31     non-malicious
Name: Label, Length: 124, dtype: object

In [27]:
clf=tree.DecisionTreeClassifier()

In [28]:
clf

DecisionTreeClassifier()

In [29]:
X_train.head

<bound method NDFrame.head of      F_1  F_2  F_3  F_4  F_5  F_6  F_7  F_8  F_9  F_10  ...  F_522  F_523  \
36     1    0    1    0    1    0    1    0    1     0  ...      0      0
158    1    0    1    0    1    0    1    0    1     0  ...      0      0
183    1    0    1    0    1    0    1    0    1     0  ...      0      0
168    1    0    1    0    1    0    1    0    1     0  ...      0      1
302    1    0    1    0    1    0    1    0    1     0  ...      0      1
..   ...  ...  ...  ...  ...  ...  ...  ...  ...   ...  ...    ...    ...
71     1    0    1    0    1    0    1    0    1     0  ...      0      0
106    1    0    1    0    1    0    1    0    1     0  ...      0      0
270    1    0    1    0    1    0    1    0    1     0  ...      0      0
348    1    0    1    0    1    0    1    0    1     0  ...      0      0
102    1    0    1    0    1    0    1    0    1     0  ...      0      0

     F_524  F_525  F_526  F_527  F_528  F_529  F_530  F_531
36       0      0      0      0      0      0      0      0
158      0      0      0      0      0      0      0      1
183      0      0      1      0      0      0      1      0
168      0      0      1      0      0      1      0      0
302      0      0      1      0      0      0      1      0
..     ...    ...    ...    ...    ...    ...    ...    ...
71       0      0      0      0      0      0      0      0
106      0      0      0      0      0      0      0      0
270      0      0      1      0      0      0      1      0
348      0      0      1      0      0      0      1      0
102      0      0      0      0      0      0      0      1

[249 rows x 531 columns]>

In [33]:


clf= clf.fit(X_train, y_train)

In [43]:
filename='filanized_model.sav'
pickle.dump(clf, open(filename,'wb'))

In [34]:
clf.predict(np.array(X_train.loc[36]).reshape(1,-1))

C:\ProgramData\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array(['non-malicious'], dtype=object)

In [37]:
confusion_matrix(y_test, clf.predict(X_test))

array([[94,  4],
       [ 1, 25]], dtype=int64)

In [39]:
y_test.value_counts()

malicious        98
non-malicious    26
Name: Label, dtype: int64